In [65]:
import numpy as np

# BASICS

In [66]:
a = np.array([1,2], dtype='int16')
print(a)

[1 2]


In [67]:
# A col
b = np.array([[9.0, 8.0, 7.0]])
print(b)

[[9. 8. 7.]]


In [68]:
# Get Dimensions
b.ndim

2

In [69]:
# Get Shape
b.shape

(1, 3)

In [70]:
# Get Type
a.dtype

dtype('int16')

In [71]:
# Get size
a.itemsize

2

In [72]:
# Get total size
a.size * a.itemsize

4

## Accessing/Changing specific elements, rows, columns, etc

In [73]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,99,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 99 14]]


In [74]:
# Get a specific element [r, c]
a[1, 5]

99

In [75]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [76]:
# Get specific column
a[:, 2]

array([ 3, 10])

In [77]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [78]:
a[1,5] = 13
print (a)

a[:,2] = 990
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[  1   2 990   4   5   6   7]
 [  8   9 990  11  12  13  14]]


#### 3d example

In [79]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [80]:
# Get specific elemt (work outside in)
b[:,:,0]

array([[1, 3],
       [5, 7]])

In [81]:
# replace the 3d element
b[:,1,:] = [[22,22],[33,33]]
print(b)

[[[ 1  2]
  [22 22]]

 [[ 5  6]
  [33 33]]]


## Initaializing Different Types of Arrays

In [82]:
# All 0s matrix
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [83]:
np.full((2,2), 67, dtype="float32")

array([[67., 67.],
       [67., 67.]], dtype=float32)

In [84]:
# Any other number (full time)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [85]:
# Random decimal number
np.random.rand(4,2)

array([[0.20035614, 0.53721139],
       [0.65234209, 0.9504469 ],
       [0.64772503, 0.76066435],
       [0.13459493, 0.90473052]])

In [86]:
# Random integer values
np.random.randint(7, size=(3,3))

array([[1, 0, 0],
       [6, 0, 0],
       [0, 0, 1]])

In [87]:
#Creates a square matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [89]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [91]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9 
print(z)

output[1:-1,1:4]  = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Be careful when copying areas

In [93]:
a = np.array([1,2,3])
b = a 
b[0] = 100 

print(a)

a = np.array([1,2,3])
b = a.copy()
b[0] =100
print(a)

[100   2   3]
[1 2 3]


## Mathematics in Numpy

In [94]:
a = np.array([1,2,3])

In [95]:
a + 2

array([3, 4, 5])

In [96]:
a - 20

array([-19, -18, -17])

In [97]:
 a * 2

array([2, 4, 6])

In [99]:
b = np.array([1,0,2,])
a + b

array([2, 2, 5])

In [100]:
a ** 2

array([1, 4, 9], dtype=int32)

In [101]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

#### Linear Algebra

In [102]:
a = np.full((2,3), 2)
print(a)

b = np.full((2,3), 2)
print(b)

# To perform matrix multiplication
np.matmul(a,b)

[[2 2 2]
 [2 2 2]]


In [104]:
#Finding the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
## Reference https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

# Determinant
# Trace
# Singular Vector Composition
# Eingenvalues
# Matrix Norm
# Inverse 


## Statistics

In [105]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
print(np.min(stats,axis=0))

print(np.min(stats))

[1 2 3]
1


In [109]:
print(np.max(stats))

6


In [110]:
np.sum(stats)

21

## Reorganizing arrays

In [120]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

print("8 by 1")
after = before.reshape((4,2))
print(after)


[[1 2 3 4]
 [5 6 7 8]]
8 by 1
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [122]:
# Verically Stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [124]:
## Horizontal Stacking
h1 = np.ones((2,4))
h2 = np.full((2,2),987)

np.hstack((h1,h2))

array([[  1.,   1.,   1.,   1., 987., 987.],
       [  1.,   1.,   1.,   1., 987., 987.]])

## Miscellaneous
### Load Data From File

In [126]:
# filedata = np.genfromtxt('data.txt', delimeter=',')

# Change tipe of read data
# filedata.astype('int32')

filedata = np.random.randint(1000, size=(3, 18))
filedata


array([[650, 155, 154, 812, 596, 631, 871, 130, 453, 604, 714, 162, 776,
        409, 933, 863,  56, 746],
       [874, 911, 705, 648, 516, 501, 225, 784, 234, 906, 552, 332,  84,
        851, 333, 523, 821, 858],
       [118, 264, 913, 819,  99, 975, 556, 313, 472, 880, 301, 541, 977,
        220, 953, 609, 369, 223]])

#### Boolean Masking and Advanced Indexing

In [127]:
filedata > 500

array([[ True, False, False,  True,  True,  True,  True, False, False,
         True,  True, False,  True, False,  True,  True, False,  True],
       [ True,  True,  True,  True,  True,  True, False,  True, False,
         True,  True, False, False,  True, False,  True,  True,  True],
       [False, False,  True,  True, False,  True,  True, False, False,
         True, False,  True,  True, False,  True,  True, False, False]])

In [129]:
filedata[filedata > 500]

array([650, 812, 596, 631, 871, 604, 714, 776, 933, 863, 746, 874, 911,
       705, 648, 516, 501, 784, 906, 552, 851, 523, 821, 858, 913, 819,
       975, 556, 880, 541, 977, 953, 609])

In [131]:
# Checking the columns in order
np.any(filedata > 500, axis = 0)

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [130]:
## Indexing with a list in Numpy
a = np.array([1,2,3,4,5,6,11,7,8,9])
a[[4,7,2]]

array([5, 7, 3])

In [133]:
print(((filedata  > 50) & (filedata < 100)))

# Checking the negetation of the above condition
print(~((filedata > 50) & (filedata < 100)))


[[False False False False False False False False False False False False
  False False False False  True False]
 [False False False False False False False False False False False False
   True False False False False False]
 [False False False False  True False False False False False False False
  False False False False False False]]
[[ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True False  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True
  False  True  True  True  True  True]
 [ True  True  True  True False  True  True  True  True  True  True  True
   True  True  True  True  True  True]]


In [135]:
question = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(question)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [137]:
# Indexing
print( question[2:4, 0:2])

print(question[[0,1,2,3],[1,2,3,4]])

[[11 12]
 [16 17]]
[ 2  8 14 20]


In [139]:
print(question[[0,4,5],3:])

[[ 4  5]
 [24 25]
 [29 30]]
